eureka:
  client:
    serviceUrl:
      defaultZone: http://18.188.51.39:8801/eureka/
  instance:
    prefer-ip-address: true
    
spring:
  zipkin:
    enabled: true
    base-url:  http://18.188.51.39:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0